### ISSUE TITLE
Doesn't Work for Softlinks

### ISSUE THREAD

**Issue by theGeekPirate** [ericek111/linux-csgo-downloadfixer#1]
Received this error, as my steam path is located inside of a soft (symbolic) link:

```Failed to fopen /mnt/btrfs/Installed/Softlinks/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/materials/paintball/pb_yellow.vtf```

EDIT: Or at least I _believe_ it's due to the softlink, could also be related to btrfs I guess

**Comment by ericek111** [comment]
Thanks for your feedback!

Is the path correct? What does `ls "/mnt/btrfs/Installed/Softlinks/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/materials/paintball"` show, please?

**Comment by theGeekPirate** [comment]
It is, ```ls "/mnt/btrfs/Installed/Softlinks/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo"``` shows a bunch of files (mostly .vpk files). The path you provided won't work since it never created the ```paintball``` folder due to this issue =b

You have no idea how much this tool means to me, thank you so much for taking the time to write it!

**Comment by ericek111** [comment]
Yes, it helped me numerous times today when I was trying a new mod.

Sorry, I noticed the bug, but I thought it was something insignificant.
The program should now properly execute `mkdir -p /path/to/csgo/and/downloaded/resource/parent` prior to downloading a file.

Update your source codes with `git pull` and recompile, please.

**Comment by theGeekPirate** [comment]
Worked great, although (at least with ```-nowrite``` set) it loops through the downloads until I manually stop it. FWIW, the ```#<num>``` output loops as well. Would you like me to create a separate issue for this?

**Comment by ericek111** [comment]
Yep, I added a 10 second delay to prevent this (so in case of a reconnect you won't have to wait too long - I think I'll make the delay configurable). I'd rather stick with the writes tho... Chance of getting VAC banned is really non-existent and the choice is there only for the most paranoid ones.

**Comment by theGeekPirate** [comment]
Gotcha, thanks again <3

**Comment by ericek111** [comment]
:) You can now change the delay like so: `./csgo_downloadfixer -nowrite 20`
