### ISSUE TITLE
Game Crashes Upon Loading

### ISSUE THREAD

**Issue by theGeekPirate** [ericek111/linux-csgo-downloadfixer#2]
Ready for a fun one?

Game crashes after the game loads for both of these servers:
192.223.24.139:27015 (as well as their other servers http://surf.ksfclan.com/connect/)
172.241.151.90:27017

```-nowrite``` flag doesn't seem to help in this case.

**Comment by ericek111** [comment]
I'll check it out, but your issue is most likely server-specific. There's no way the game would crash with the `-nowrite` option.

**Comment by theGeekPirate** [comment]
I wasn't thinking correctly, I was imagining that your tool was corrupting some downloads, but I had forgotten that CS:GO already verifies files while connecting, and tells you when it discovers a corrupted file.

I wonder if this issue has anything to do with why the CS:GO devs never bothered implementing a file downloader? Interesting to think about at least.

Sorry about that!
