### ISSUE TITLE
Game Crashes After Map Downloads - Map Files Download, Do Not Extract Correctly

### ISSUE THREAD

**Issue by skokkk** [ericek111/linux-csgo-downloadfixer#3]
Hey there!

Thank you a lot for this fix. I am having some trouble to get it working though currently. I have tried the -nowrite flag, made sure I'm running as sudo, etc...

When looking further in my maps folder I see the .bsp.bz2 files (and the ".nav" and ".bsp" - will explain now why there are quotes) are there and successfully downloaded.

I can see the files were downloaded, however the FastDL servers that most community servers use have a .bsp and a .bsp.bz2, but in the case of only a .bsp.bz2 being available (and logically one should download the compressed file instead of the bigger version of the same file?), this is where my problem starts. I get the error below (a 404 error, as expected - since there is no surf_666.bsp on that FastDL server). This is the content of surf_666.bsp:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>
```

However, it seems to still download the .bz2 files, maybe do some check if there is already a .bz2 file available on the FastDL server, don't download the .bsp and extract the .bz2.

Here is the output of your application:
```

[shock@laptop linux-csgo-downloadfixer]$ sudo ./csgo_downloadfixer
Waiting for csgo.
CSGO Process Located [/home/shock/Steam/steamapps/common/Counter-Strike Global Offensive/csgo_linux64][9792]

engine_client.so: [7f5ea04b3000][7f5ea0ffb000][/home/shock/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so]
>>> found TheDownloadManager mov: 0x7f5ea0a0c251

>>> Address of TheDownloadManager: 0x7f5ea14adac0

Game ended.
Waiting for csgo.
CSGO Process Located [/home/shock/Steam/steamapps/common/Counter-Strike Global Offensive/csgo_linux64][270f]

engine_client.so: [7fd137f32000][7fd138a7a000][/home/shock/Steam/steamapps/common/Counter-Strike Global Offensive/bin/linux64/engine_client.so]
>>> found TheDownloadManager mov: 0x7fd13848b251

>>> Address of TheDownloadManager: 0x7fd138f2cac0

#0 /  Downloading http://csgo-fastdl.specternetworks.com/csgo/maps/surf_666.bsp.bz2 to /home/shock/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/maps/surf_666.bsp.bz2
#1 /  Downloading http://csgo-fastdl.specternetworks.com/csgo/maps/surf_666.bsp to /home/shock/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/maps/surf_666.bsp
#2 /  Downloading http://csgo-fastdl.specternetworks.com/csgo/maps/surf_666.nav.bz2 to /home/shock/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/maps/surf_666.nav.bz2
#3 /  Downloading http://csgo-fastdl.specternetworks.com/csgo/maps/surf_666.nav to /home/shock/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/maps/surf_666.nav
0
0
Game ended.
```

**Comment by ericek111** [comment]
Yes, I've thought of that. I may implement it. Thanks for feedback!

**Comment by ericek111** [comment]
I've added the BZ2 support. Please, recompile your program with `git pull && make` and append a new CLI argument `-bz2`, because I've disabled the feature by default.

**Comment by theGeekPirate** [comment]
With ```-bz2```, it doesn't look like anything is being downloaded at all.

I believe this may actually be related to https://github.com/ericek111/linux-csgo-downloadfixer/issues/2 , as by the looks of it, those two servers _only_ provide bz2 files.

I also tested on a server that provides both (```192.223.29.148:27015```), and ```-bz2``` simply doesn't download anything once more, but removing the flag does make the program work correctly.

We're close, keep up the amazing work!

P.S. With ```-bz2```, when I Ctrl+C to quit, it prints ```bzip2 command not available! Install bzip2.```, but ```which bzip2``` returns ```/usr/bin/bzip2```, so it _is_ installed correctly.

**Comment by ericek111** [comment]
Interesting. Try executing `bzip2 --version` in the very same shell window you're launching the tool from, please.
`-bz2` flag should execute `bzip2 -dkq [file]` after a file ending with .bz2 is downloaded.

**Comment by HeyItsBATMAN** [comment]
Also getting `bzip2 command not available! Install bzip2`
`bzip2 --version` outputs `bzip2, a block-sorting file compressor.  Version 1.0.6, 6-Sept-2010`

I commented out the bzip2 check `int ret = system("bzip2 --version > /dev/null 2>&1");`
The downloading seems to be working fine, but I'm still getting occasional crashes
Gonna test behaviour on a few servers and report back

**Comment by theGeekPirate** [comment]
Same as HeyItsBATMAN (using Arch Linux here) ```Version 1.0.6, 6-Sept-2010```

**Comment by skokkk** [comment]
I have also been experiencing these crashes recently. The download fixed freezes, then when I press ctrl + c it goes to the next file, etc.. (I need to use -bz2) I experience the same thing to do with bzip2.

Psssst.
bzip2, a block-sorting file compressor.  Version 1.0.6, 6-Sept-2010.

   usage: bzip2 [flags and input files in any order]

   -h --help           print this message
   -d --decompress     force decompression
   -z --compress       force compression
   -k --keep           keep (don't delete) input files
   -f --force          overwrite existing output files
   -t --test           test compressed file integrity
   -c --stdout         output to standard out
   -q --quiet          suppress noncritical error messages
   -v --verbose        be verbose (a 2nd -v gives more)
   -L --license        display software version & license
   -V --version        display software version & license
   -s --small          use less memory (at most 2500k)
   -1 .. -9            set block size to 100k .. 900k
   --fast              alias for -1
   --best              alias for -9

   If invoked as `bzip2', default action is to compress.
              as `bunzip2',  default action is to decompress.
              as `bzcat', default action is to decompress to stdout.

   If no file names are given, bzip2 compresses or decompresses
   from standard input to standard output.  You can combine
   short flags, so `-v -4' means the same as -v4 or -4v, &c.

**Comment by joaomoises99** [comment]
I think I know what happens!
The bz2 isn't working proprely.
Already can reach server! I just go to cs go dir, go to maps and see what's inside .bz2, then I saw inside .bz2 files, there's a .bsp or a .nav bigger than the extracted one. I've deleted files and extract by my own.
edit: Some .bz2 files are corrupted or something, then I've seen a message that there's a plugin... :thinking: 
edit2: but, i think my final idea is concluded. this algorithm isn't unzipping propraly, there's also other textures, for e.g, that didn't have been unzipped.

**Comment by skokkk** [comment]
Simply edit the source code, look for the line that runs the bz2 command
extract, and just change it with the accepted standard (according to gzip's
man page) "gunzip". The second field with the flags. Remove the flags in
there, since gunzip already contains the needed flags. Good luck!

**Comment by joaomoises99** [comment]
Did anyone already tried @skokkk tip?

**Comment by Korriee** [comment]
I tried @skokkk 's response, same thing though just corruption when extracting so i switched it to lbzip2 and it seems to be working, i'm running manjaro. If you wanna try it out @jawkPT 
https://pastebin.com/raw/2TgmreHF  (my main.cpp file, replace it with this & cmake . / make) make sure to deleted the corrupted maps from your folder. also install lbzip2, new -bz2 option is -lbzip2

**Comment by Sixcross** [comment]
I first tried @ericek111 solution, but it got stuck Skipping a ton of files. Still could not connect to the server.
Then i closed it and tried to join without (i thought that all filed should be loaded anyway) but then csgo just closed itself (this issue here).

Well i tired @Korriee 's solution, but this did not change anyting (still crashing). After that i tired @skokkk  's solution which got me into the Server and i could play. I still had issues with models and textures displaying error.

So i thought myself: "Probably the first extraction attempt were also corrupted?! Why not delete all maps, sounds, textures and models in csgo, verfy integrity (to download standard files) and run @skokkk 's solution again?"

Guess what... its again crashing -.-' right after downloading the maps.
Probably the textures need to be extracted in another way?

**Comment by ericek111** [comment]
Probably the original files are not present on the server, only zipped ones. I already have it fixed and I'll publish it tomorrow. rn im tired af so gn.

**Comment by ericek111** [comment]
Okay. I've enabled the BZ2 decompression by default. It should also properly handle 404s (files requested, but not present on the fastDL server). Recompile again using `git pull && make`, please.

Sometimes you have to join server repeatedly using `retry` to download everything.

**Comment by Korriee** [comment]
So far so good! We all appreciate it very very much.

**Comment by ericek111** [comment]
Closing as resolved.
