### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by jangleman** [ericek111/linux-csgo-downloadfixer#4]
I get this error: 
CMakeFiles/csgo_downloadfixer.dir/main.cpp.o:(.eh_frame+0x20b): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
CMakeFiles/csgo_downloadfixer.dir/build.make:120: recipe for target 'csgo_downloadfixer' failed
make[2]: *** [csgo_downloadfixer] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/csgo_downloadfixer.dir/all' failed
make[1]: *** [CMakeFiles/csgo_downloadfixer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

After I try to make the program. Any solutions?

**Comment by ericek111** [comment]
https://stackoverflow.com/questions/6045809/link-error-undefined-reference-to-gxx-personality-v0-and-g
