### ISSUE TITLE
Linking Error

### ISSUE THREAD

**Issue by carlzoo** [ericek111/linux-csgo-downloadfixer#8]
When I try to compile: I get a long error stacktrace

> carl@potato:/tmp/linux-csgo-downloadfixer$ make
[ 33%] Linking CXX executable csgo_downloadfixer
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::Handle(int)':
remote.cpp:(.text+0x239): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text+0x26e): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
remote.cpp:(.text+0x289): undefined reference to `std::ostream::operator<<(int)'
remote.cpp:(.text+0x2b2): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::str() const'
remote.cpp:(.text+0x2cf): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
remote.cpp:(.text+0x2de): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x2ed): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
remote.cpp:(.text+0x311): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
remote.cpp:(.text+0x33c): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::Handle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
remote.cpp:(.text+0x392): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text+0x3b4): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
remote.cpp:(.text+0x3d5): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
remote.cpp:(.text+0x400): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::clear()'
remote.cpp:(.text+0x423): undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::basic_istringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)'
remote.cpp:(.text+0x440): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
remote.cpp:(.text+0x45d): undefined reference to `std::istream::operator>>(int&)'
remote.cpp:(.text+0x46c): undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()'
remote.cpp:(.text+0x480): undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()'
remote.cpp:(.text+0x4ab): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::GetPath[abi:cxx11]()':
remote.cpp:(.text+0x54d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x559): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x57e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x58f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o:remote.cpp:(.text+0x61f): more undefined references to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()' follow
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::IsRunning()':
remote.cpp:(.text+0x710): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
remote.cpp:(.text+0x756): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x780): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::ParseMaps()':
remote.cpp:(.text+0xb20): undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)'
remote.cpp:(.text+0xb2f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0xb3e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0xb4d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text+0xb66): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
remote.cpp:(.text+0xb7b): undefined reference to `std::basic_ios<char, std::char_traits<char> >::operator bool() const'
remote.cpp:(.text+0xba1): undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::basic_istringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)'
remote.cpp:(.text+0xbb0): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text+0xbbf): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text+0xbce): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text+0xbdd): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text+0xbec): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text+0xc05): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
remote.cpp:(.text+0xc1a): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
remote.cpp:(.text+0xc2f): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
remote.cpp:(.text+0xc44): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
remote.cpp:(.text+0xc59): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
remote.cpp:(.text+0xc6e): undefined reference to `std::basic_ios<char, std::char_traits<char> >::operator bool() const'
remote.cpp:(.text+0xc85): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text+0xcaa): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::length() const'
remote.cpp:(.text+0xcde): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
remote.cpp:(.text+0xcf4): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
remote.cpp:(.text+0xd08): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0xd35): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
remote.cpp:(.text+0xd55): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
remote.cpp:(.text+0xd6e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char, unsigned long) const'
remote.cpp:(.text+0xd84): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0xd9d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
remote.cpp:(.text+0xdc7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
remote.cpp:(.text+0xde0): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
remote.cpp:(.text+0xdef): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0xe00): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::clear()'
remote.cpp:(.text+0xe35): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char, unsigned long) const'
remote.cpp:(.text+0xe55): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char, unsigned long) const'
remote.cpp:(.text+0xe7e): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
remote.cpp:(.text+0xea6): undefined reference to `std::ostream::operator<<(std::ios_base& (*)(std::ios_base&))'
remote.cpp:(.text+0xece): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
remote.cpp:(.text+0xee0): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
remote.cpp:(.text+0xeef): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0xf08): undefined reference to `std::istream::operator>>(unsigned long&)'
remote.cpp:(.text+0xf20): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
remote.cpp:(.text+0xf3a): undefined reference to `std::ostream::operator<<(std::ios_base& (*)(std::ios_base&))'
remote.cpp:(.text+0xf4c): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
remote.cpp:(.text+0xf70): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
remote.cpp:(.text+0xf82): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
remote.cpp:(.text+0xf91): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0xfae): undefined reference to `std::istream::operator>>(unsigned long&)'
remote.cpp:(.text+0xfc6): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
remote.cpp:(.text+0xfee): undefined reference to `std::ostream::operator<<(std::ios_base& (*)(std::ios_base&))'
remote.cpp:(.text+0x1016): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
remote.cpp:(.text+0x1028): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
remote.cpp:(.text+0x1037): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1054): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><std::char_traits<char> >(std::basic_istream<char, std::char_traits<char> >&, unsigned char&)'
remote.cpp:(.text+0x106c): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
remote.cpp:(.text+0x1086): undefined reference to `std::ostream::operator<<(std::ios_base& (*)(std::ios_base&))'
remote.cpp:(.text+0x1098): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
remote.cpp:(.text+0x10bc): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
remote.cpp:(.text+0x10ce): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
remote.cpp:(.text+0x10dd): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x10fa): undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><std::char_traits<char> >(std::basic_istream<char, std::char_traits<char> >&, unsigned char&)'
remote.cpp:(.text+0x1112): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
remote.cpp:(.text+0x112c): undefined reference to `std::ostream::operator<<(std::ios_base& (*)(std::ios_base&))'
remote.cpp:(.text+0x1141): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
remote.cpp:(.text+0x115e): undefined reference to `std::istream::operator>>(unsigned long&)'
remote.cpp:(.text+0x1176): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
remote.cpp:(.text+0x1193): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
remote.cpp:(.text+0x11b0): undefined reference to `std::istream::operator>>(unsigned long&)'
remote.cpp:(.text+0x11c4): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigned long)'
remote.cpp:(.text+0x11e6): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigned long)'
remote.cpp:(.text+0x1208): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigned long)'
remote.cpp:(.text+0x122a): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigned long)'
remote.cpp:(.text+0x1247): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty() const'
remote.cpp:(.text+0x126f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
remote.cpp:(.text+0x128a): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char, unsigned long) const'
remote.cpp:(.text+0x12aa): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
remote.cpp:(.text+0x12ce): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
remote.cpp:(.text+0x12eb): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
remote.cpp:(.text+0x12fa): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1326): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
remote.cpp:(.text+0x1344): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1353): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1362): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1371): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1380): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o:remote.cpp:(.text+0x138f): more undefined references to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()' follow
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::ParseMaps()':
remote.cpp:(.text+0x139e): undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()'
remote.cpp:(.text+0x13b2): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x13c1): undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::~basic_ifstream()'
remote.cpp:(.text+0x13ec): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1400): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x141d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1431): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1445): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o:remote.cpp:(.text+0x1459): more undefined references to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()' follow
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::ParseMaps()':
remote.cpp:(.text+0x146d): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
remote.cpp:(.text+0x1495): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x14a9): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x14b8): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x14c7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x14d6): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o:remote.cpp:(.text+0x14e5): more undefined references to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()' follow
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::ParseMaps()':
remote.cpp:(.text+0x14f4): undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()'
remote.cpp:(.text+0x1508): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1517): undefined reference to `std::basic_ifstream<char, std::char_traits<char> >::~basic_ifstream()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::GetSymbolicLinkTarget(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
remote.cpp:(.text+0x1571): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
remote.cpp:(.text+0x15bf): undefined reference to `std::allocator<char>::allocator()'
remote.cpp:(.text+0x15df): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
remote.cpp:(.text+0x15ee): undefined reference to `std::allocator<char>::~allocator()'
remote.cpp:(.text+0x15ff): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text+0x1613): undefined reference to `std::allocator<char>::~allocator()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::FindProcessByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, remote::Handle*)':
remote.cpp:(.text+0x1687): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty() const'
remote.cpp:(.text+0x1712): undefined reference to `std::allocator<char>::allocator()'
remote.cpp:(.text+0x1733): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
remote.cpp:(.text+0x1773): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x177f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x178e): undefined reference to `std::allocator<char>::~allocator()'
remote.cpp:(.text+0x179d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
remote.cpp:(.text+0x17cd): undefined reference to `std::allocator<char>::allocator()'
remote.cpp:(.text+0x17ee): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
remote.cpp:(.text+0x180d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x181c): undefined reference to `std::allocator<char>::~allocator()'
remote.cpp:(.text+0x1881): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty() const'
remote.cpp:(.text+0x18aa): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char, unsigned long) const'
remote.cpp:(.text+0x18ea): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const'
remote.cpp:(.text+0x1900): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
remote.cpp:(.text+0x193d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x195e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x19b7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1a07): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1a18): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1a2c): undefined reference to `std::allocator<char>::~allocator()'
remote.cpp:(.text+0x1a46): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1a5a): undefined reference to `std::allocator<char>::~allocator()'
remote.cpp:(.text+0x1a6b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1a7f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text+0x1a9f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::MapModuleMemoryRegion::MapModuleMemoryRegion()':
remote.cpp:(.text._ZN6remote21MapModuleMemoryRegionC2Ev[_ZN6remote21MapModuleMemoryRegionC5Ev]+0x18): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
remote.cpp:(.text._ZN6remote21MapModuleMemoryRegionC2Ev[_ZN6remote21MapModuleMemoryRegionC5Ev]+0x28): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::MapModuleMemoryRegion::~MapModuleMemoryRegion()':
remote.cpp:(.text._ZN6remote21MapModuleMemoryRegionD2Ev[_ZN6remote21MapModuleMemoryRegionD5Ev]+0x18): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
remote.cpp:(.text._ZN6remote21MapModuleMemoryRegionD2Ev[_ZN6remote21MapModuleMemoryRegionD5Ev]+0x28): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::~Handle()':
remote.cpp:(.text._ZN6remote6HandleD2Ev[_ZN6remote6HandleD5Ev]+0x28): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `remote::Handle::operator=(remote::Handle const&)':
remote.cpp:(.text._ZN6remote6HandleaSERKS0_[_ZN6remote6HandleaSERKS0_]+0x43): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
remote.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_OS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_OS8_]+0x25): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::insert(unsigned long, char const*)'
remote.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_OS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_OS8_]+0x3f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
CMakeFiles/csgo_downloadfixer.dir/remote.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
...

Looks like a familiar error - but I'm not sure how cmake works.

**Comment by ericek111** [comment]
I think it's a mismatch between your compiler and linker.

Try this, please: https://stackoverflow.com/questions/33394934/converting-std-cxx11string-to-stdstring
