### ISSUE TITLE
Throws errors when compiling

### ISSUE THREAD

**Issue by samabenie1** [ericek111/linux-csgo-downloadfixer#9]
When running "make", terminal throws the following error.

linux-csgo-downloadfixer/main.cpp:13:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
CMakeFiles/csgo_downloadfixer.dir/build.make:86: recipe for target 'CMakeFiles/csgo_downloadfixer.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/csgo_downloadfixer.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/csgo_downloadfixer.dir/all' failed
make[1]: *** [CMakeFiles/csgo_downloadfixer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ericek111** [comment]
Is it that difficult to read the README?

```
sudo apt-get install make cmake gcc git libcurl-dev
```

**Comment by samabenie1** [comment]
Yup. I'm a dumb.
